# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_enfermedades',
            fields=[
                ('id_enfermedad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='datos_generales',
            fields=[
                ('cod_expediente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('edad_registro', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=8)),
                ('genero', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('nombre_resp', models.CharField(max_length=100)),
                ('motivo_consulta', models.CharField(max_length=500)),
                ('fechaRegistro', models.DateTimeField()),
                ('fecha_hora_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='estado_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio_salud', models.BooleanField()),
                ('detalle_enf_operacion', models.CharField(blank=True, max_length=500, null=True)),
                ('detalle_medicamento', models.CharField(blank=True, max_length=30, null=True)),
                ('detalle_otra_enfermedad', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.datos_generales')),
            ],
            options={
                'ordering': ['cod_expediente'],
            },
        ),
        migrations.AddField(
            model_name='estado_general',
            name='fichas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas'),
        ),
        migrations.AddField(
            model_name='estado_general',
            name='otras_enfermedades',
            field=models.ManyToManyField(blank=True, null=True, to='informacion.catalogo_enfermedades'),
        ),
        migrations.AlterUniqueTogether(
            name='fichas',
            unique_together=set([('cod_expediente', 'numero')]),
        ),
    ]
