# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linea_media_facial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mx', models.IntegerField()),
                ('mx_desviacion', models.IntegerField()),
                ('md', models.IntegerField()),
                ('md_desviacion', models.IntegerField()),
                ('datos_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.datos_generales')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='registro_mordidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuad_superior', models.IntegerField()),
                ('pieza_superior', models.IntegerField()),
                ('cuad_inferior', models.IntegerField()),
                ('pieza_inferior', models.IntegerField()),
                ('datos_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.datos_generales')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='sobremordidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal', models.IntegerField()),
                ('vertical', models.IntegerField()),
                ('datos_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.datos_generales')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
    ]
